apiVersion: apps/v1
kind: Deployment
metadata:
  name: srujan-financial
spec:
  selector:
    matchLabels:
      app: srujan-financial
  replicas: 1
  template:
    metadata:
      labels:
        app: srujan-financial
    spec:
      containers:
        - name: srujan-financial-app
          image: srujan-financial-image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
